"""add testcase and testcase_category tables

Revision ID: 0df275bcfd1b
Revises: 257947331d01
Create Date: 2026-01-05 10:43:51.431479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0df275bcfd1b'
down_revision: Union[str, None] = '257947331d01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('testcase_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['testcase_categories.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_testcase_categories_id'), 'testcase_categories', ['id'], unique=False)
    op.create_table('testcases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('case_number', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('type', sa.Enum('FUNCTIONAL', 'PERFORMANCE', 'SECURITY', 'COMPATIBILITY', 'SMOKE', 'REGRESSION', name='testcasetype'), nullable=False),
    sa.Column('status', sa.Enum('NORMAL', 'DEPRECATED', 'DRAFT', name='testcasestatus'), nullable=False),
    sa.Column('priority', sa.Enum('HIGH', 'MEDIUM', 'LOW', name='testcasepriority'), nullable=False),
    sa.Column('precondition', sa.Text(), nullable=True),
    sa.Column('steps', sa.Text(), nullable=True),
    sa.Column('expected_result', sa.Text(), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['testcase_categories.id'], ),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_testcases_case_number'), 'testcases', ['case_number'], unique=True)
    op.create_index(op.f('ix_testcases_category_id'), 'testcases', ['category_id'], unique=False)
    op.create_index(op.f('ix_testcases_id'), 'testcases', ['id'], unique=False)
    # Add testcase_seq column with default value for SQLite compatibility
    op.add_column('projects', sa.Column('testcase_seq', sa.Integer(), nullable=True, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'testcase_seq')
    op.drop_index(op.f('ix_testcases_id'), table_name='testcases')
    op.drop_index(op.f('ix_testcases_category_id'), table_name='testcases')
    op.drop_index(op.f('ix_testcases_case_number'), table_name='testcases')
    op.drop_table('testcases')
    op.drop_index(op.f('ix_testcase_categories_id'), table_name='testcase_categories')
    op.drop_table('testcase_categories')
    # ### end Alembic commands ###
