"""add developer tester dates to requirements and tasks

Revision ID: ba884bada0a1
Revises: 29cb5453617e
Create Date: 2026-01-04 18:07:42.673705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba884bada0a1'
down_revision: Union[str, None] = '29cb5453617e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # SQLite doesn't support ALTER COLUMN, skip those operations
    # Only add new columns for requirements and tasks
    op.add_column('requirements', sa.Column('developer_id', sa.Integer(), nullable=True))
    op.add_column('requirements', sa.Column('tester_id', sa.Integer(), nullable=True))
    op.add_column('requirements', sa.Column('start_date', sa.Date(), nullable=True))
    op.add_column('requirements', sa.Column('end_date', sa.Date(), nullable=True))
    op.add_column('tasks', sa.Column('developer_id', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('tester_id', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('start_date', sa.Date(), nullable=True))
    op.add_column('tasks', sa.Column('end_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'end_date')
    op.drop_column('tasks', 'start_date')
    op.drop_column('tasks', 'tester_id')
    op.drop_column('tasks', 'developer_id')
    op.drop_column('requirements', 'end_date')
    op.drop_column('requirements', 'start_date')
    op.drop_column('requirements', 'tester_id')
    op.drop_column('requirements', 'developer_id')
    # ### end Alembic commands ###
