"""add_updated_at_and_mentions_to_comments

Revision ID: cfab7e244d6d
Revises: d30e8297a96a
Create Date: 2026-01-04 11:09:22.204995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfab7e244d6d'
down_revision: Union[str, None] = 'd30e8297a96a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add columns with proper defaults for SQLite
    with op.batch_alter_table('bug_comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mentioned_user_ids', sa.JSON(), nullable=False, server_default='[]'))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=False))
    
    # Set initial value for updated_at from created_at for existing rows
    op.execute('UPDATE bug_comments SET updated_at = created_at WHERE updated_at IS NULL')
    
    op.create_foreign_key(None, 'bugs', 'requirements', ['requirement_id'], ['id'])
    op.create_foreign_key(None, 'bugs', 'sprints', ['sprint_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bugs', type_='foreignkey')
    op.drop_constraint(None, 'bugs', type_='foreignkey')
    
    with op.batch_alter_table('bug_comments', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('mentioned_user_ids')
    # ### end Alembic commands ###
