"""add sprint requirement tables and bug fk columns

Revision ID: d30e8297a96a
Revises: 06b49615f168
Create Date: 2026-01-04 09:18:00.565414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd30e8297a96a'
down_revision: Union[str, None] = '06b49615f168'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sprints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('goal', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PLANNING', 'ACTIVE', 'COMPLETED', name='sprintstatus'), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sprints_id'), 'sprints', ['id'], unique=False)
    op.create_index(op.f('ix_sprints_project_id'), 'sprints', ['project_id'], unique=False)
    op.create_table('requirements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('sprint_id', sa.Integer(), nullable=True),
    sa.Column('requirement_number', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'APPROVED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='requirementstatus'), nullable=False),
    sa.Column('priority', sa.Enum('HIGH', 'MEDIUM', 'LOW', name='requirementpriority'), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('assignee_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assignee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['sprint_id'], ['sprints.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_requirements_id'), 'requirements', ['id'], unique=False)
    op.create_index(op.f('ix_requirements_project_id'), 'requirements', ['project_id'], unique=False)
    op.create_index(op.f('ix_requirements_requirement_number'), 'requirements', ['requirement_number'], unique=True)
    op.create_index(op.f('ix_requirements_sprint_id'), 'requirements', ['sprint_id'], unique=False)
    # Add columns to bugs (SQLite batch mode)
    with op.batch_alter_table('bugs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sprint_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('requirement_id', sa.Integer(), nullable=True))

    # Create indexes separately
    op.create_index('ix_bugs_sprint_id', 'bugs', ['sprint_id'], unique=False)
    op.create_index('ix_bugs_requirement_id', 'bugs', ['requirement_id'], unique=False)

    # Add column to projects (SQLite batch mode)
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('requirement_seq', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('requirement_seq')

    # Drop indexes first
    op.drop_index('ix_bugs_requirement_id', table_name='bugs')
    op.drop_index('ix_bugs_sprint_id', table_name='bugs')

    with op.batch_alter_table('bugs', schema=None) as batch_op:
        batch_op.drop_column('requirement_id')
        batch_op.drop_column('sprint_id')

    op.drop_index(op.f('ix_requirements_sprint_id'), table_name='requirements')
    op.drop_index(op.f('ix_requirements_requirement_number'), table_name='requirements')
    op.drop_index(op.f('ix_requirements_project_id'), table_name='requirements')
    op.drop_index(op.f('ix_requirements_id'), table_name='requirements')
    op.drop_table('requirements')
    op.drop_index(op.f('ix_sprints_project_id'), table_name='sprints')
    op.drop_index(op.f('ix_sprints_id'), table_name='sprints')
    op.drop_table('sprints')
    # ### end Alembic commands ###
